// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBrbdh0xhAFN3msNPXvmgp-dtISUcp0xkk",
    authDomain: "finalartem-483ea.firebaseapp.com",
    databaseURL: "https://finalartem-483ea-default-rtdb.firebaseio.com",
    projectId: "finalartem-483ea",
    storageBucket: "finalartem-483ea.appspot.com",
    messagingSenderId: "641411852224",
    appId: "1:641411852224:web:aa1a305b3b3f8822f5ca25",
    measurementId: "G-JSV8G943G6",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNgqsyl4WMQQa2Gk8X1Bfpm4QbdQURc7w',
    appId: '1:641411852224:android:4d347403291eade8f5ca25',
    messagingSenderId: '641411852224',
    projectId: 'finalartem-483e',
    databaseURL: 'https://finalartem-483ea-default-rtdb.firebaseio.com/',
    storageBucket: 'finalartem-483ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi5Ba6vf-zWNcWlYEPbhhaN-Cn7OJd11g',
    appId: '1:1023875049222:ios:e9229f81a6d4775aa22087',
    messagingSenderId: '641411852224',
    projectId: 'artemfirebase',
    databaseURL: 'https://artemfirebase-default-rtdb.firebaseio.com',
    storageBucket: 'finalartem-483ea.appspot.com',
    iosClientId:
        '1023875049222-8rtrr0pgsdk7qhe1p89bjhdsng1g3beo.apps.googleusercontent.com',
    iosBundleId: 'com.example.essai5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi5Ba6vf-zWNcWlYEPbhhaN-Cn7OJd11g',
    appId: '1:1023875049222:ios:e9229f81a6d4775aa22087',
    messagingSenderId: '641411852224',
    projectId: 'artemfirebase',
    databaseURL: 'https://artemfirebase-default-rtdb.firebaseio.com',
    storageBucket: 'finalartem-483ea.appspot.com',
    iosClientId:
        '1023875049222-8rtrr0pgsdk7qhe1p89bjhdsng1g3beo.apps.googleusercontent.com',
    iosBundleId: 'com.example.essai5',
  );
}
