// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIliSNkJYk9p9OM1ev76MnoejxxftV7JI',
    appId: '1:1023875049222:web:c17d8381d5878553a22087',
    messagingSenderId: '1023875049222',
    projectId: 'artemfirebase',
    authDomain: 'artemfirebase.firebaseapp.com',
    databaseURL: 'https://artemfirebase-default-rtdb.firebaseio.com',
    storageBucket: 'artemfirebase.appspot.com',
    measurementId: 'G-1YR93RT252',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoxbx90NhZ5eR-88vkJ_YWDXGidhSGL50',
    appId: '1:1023875049222:android:411152b1f79175c5a22087',
    messagingSenderId: '1023875049222',
    projectId: 'artemfirebase',
    databaseURL: 'https://artemfirebase-default-rtdb.firebaseio.com',
    storageBucket: 'artemfirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi5Ba6vf-zWNcWlYEPbhhaN-Cn7OJd11g',
    appId: '1:1023875049222:ios:e9229f81a6d4775aa22087',
    messagingSenderId: '1023875049222',
    projectId: 'artemfirebase',
    databaseURL: 'https://artemfirebase-default-rtdb.firebaseio.com',
    storageBucket: 'artemfirebase.appspot.com',
    iosClientId:
        '1023875049222-8rtrr0pgsdk7qhe1p89bjhdsng1g3beo.apps.googleusercontent.com',
    iosBundleId: 'com.example.essai5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi5Ba6vf-zWNcWlYEPbhhaN-Cn7OJd11g',
    appId: '1:1023875049222:ios:e9229f81a6d4775aa22087',
    messagingSenderId: '1023875049222',
    projectId: 'artemfirebase',
    databaseURL: 'https://artemfirebase-default-rtdb.firebaseio.com',
    storageBucket: 'artemfirebase.appspot.com',
    iosClientId:
        '1023875049222-8rtrr0pgsdk7qhe1p89bjhdsng1g3beo.apps.googleusercontent.com',
    iosBundleId: 'com.example.essai5',
  );
}
